services:
  - type: web
    name: campus-found-it
    env: node
    buildCommand: "cd frontend && npm install && npm run build && cd ../backend && npm install && rm -rf public && mv ../frontend/dist public"
    startCommand: "cd backend && node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false
